site_name: Python 數據結構與算法影片教程
theme: readthedocs
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True  #for use of inline $..$

pages:
    - 課程簡介: 'index.md'
    - 00_課程簡介之笨方法学算法: '00_課程簡介之笨方法学算法/why_and_how_to_learn.md'
    - 01_抽象數據類型和面向對象编程: '01_抽象數據類型和面向對象编程/ADT_OOP.md'
    - 02_數组和列表: '02_數组和列表/array_and_list.md'
    - 03_鏈表: '03_鏈表/linked_list.md'
    - 04_陣列: '04_陣列/queue.md'
    - 05_堆疊: '05_堆疊/stack.md'
    - 06_算法分析: '06_算法分析/big_o.md'
    - 07_哈希表: '07_哈希表/hashtable.md'
    - 08_字典: '08_字典/dict.md'
    - 09_集合: '09_集合/set.md'
    - 10_遞迴: '10_遞迴/recursion.md'
    - 11_線性查找與二分查找: '11_線性查找與二分查找/search.md'
    - 12_基本排序算法: '12_基本排序算法/basic_sort.md'
    - 13_高級排序算法:
      - 高級排序算法: '13_高級排序算法/advanced_sorting.md'
      - 分治法與归並排序: '13_高級排序算法/merge_sort.md'
      - 快速排序: '13_高級排序算法/quick_sort.md'
    - 14_樹與二叉樹: '14_樹與二叉樹/tree.md'
    - 15_堆和堆排序: '15_堆與堆排序/heap_and_heapsort.md'
    - 16_優先級陣列: '16_優先級陣列/priority_queue.md'
    - 17_二叉查找樹: '17_二叉查找樹/binary_search_tree.md'
    - 18_图與图的遍历: '18_图與图的遍历/graph.md'
    - 19_python内置常用算法和數據結構: '19_python内置常用算法和數據結構/builtins.md'
    - 20_面試指南: '20_面試指南/interview.md'
